services:
  - type: web
    name: org-management-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    runtime:
      pythonVersion: 3.11.6
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: MONGO_DB
        sync: false
      - key: JWT_ALGORITHM
        sync: false
      - key: JWT_EXPIRES_MINUTES
        sync: false
